/** Purpose: Accessible owner-only account modal; no email verification or password strength scoring. */
'use client';
import {useEffect,useRef,useState} from 'react';
import styles from './CreateUser.module.css';
export default function CreateUser({en=false}){
 const dialog=useRef(null),form=useRef(null);const [roles,setRoles]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');const t=(a,b)=>en?b:a;
 useEffect(()=>{let live=true;fetch('/api/users/create',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>{if(live&&data?.canCreate)setRoles(data.roles);}).catch(()=>{});return()=>{live=false};},[]);
 const messages={EMAIL:t('Skráðu gilt netfang.','Enter a valid email.'),EMAIL_MATCH:t('Netföngin verða að vera eins.','Emails must match.'),PASSWORD:t('Lykilorð vantar eða er of langt.','Password is required or too long.'),PASSWORD_MATCH:t('Lykilorðin verða að vera eins.','Passwords must match.'),EXISTS:t('Netfangið er þegar skráð.','This email is already registered.'),FORBIDDEN:t('Aðeins eigandinn má stofna notendur.','Only the owner may create users.')};
 async function submit(event){event.preventDefault();const input=Object.fromEntries(new FormData(event.currentTarget));setError('');setSuccess('');if(input.email.trim().toLowerCase()!==input.emailAgain.trim().toLowerCase()){setError(messages.EMAIL_MATCH);return;}if(input.password!==input.passwordAgain){setError(messages.PASSWORD_MATCH);return;}setBusy(true);try{const response=await fetch('/api/users/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const result=await response.json();if(!response.ok){setError(messages[result.error]||t('Ekki tókst að stofna notanda.','Could not create user.'));return;}form.current.reset();setSuccess(t('Notandi stofnaður: ','User created: ')+result.email);}catch{setError(t('Tenging brást.','Connection failed.'));}finally{setBusy(false);}}
 if(!roles.length)return null;
 return <><button className={styles.trigger} type="button" onClick={()=>dialog.current.showModal()}>{t('Búa til notanda','Create new user')}</button><dialog ref={dialog} className={styles.dialog} aria-labelledby="create-user-title" onCancel={e=>{if(busy)e.preventDefault();}} onClose={()=>{form.current?.reset();setError('');setSuccess('');}}><form ref={form} onSubmit={submit} className={styles.form}><header><h2 id="create-user-title">{t('Búa til notanda','Create new user')}</h2><button type="button" disabled={busy} onClick={()=>dialog.current.close()} aria-label={t('Loka','Close')}>×</button></header><p>{t('Aðgangurinn virkar strax. Enginn staðfestingarpóstur er sendur.','The account works immediately. No confirmation email is sent.')}</p><label>{t('Nafn (valfrjálst)','Name (optional)')}<input name="name" maxLength={120} autoComplete="off"/></label>{[['email','Netfang','Email'],['emailAgain','Netfang aftur','Repeat email']].map(([name,is,eng])=><label key={name}>{t(is,eng)}<input name={name} type="email" required maxLength={254} autoComplete="off"/></label>)}{[['password','Lykilorð','Password'],['passwordAgain','Lykilorð aftur','Repeat password']].map(([name,is,eng])=><label key={name}>{t(is,eng)}<input name={name} type="password" required maxLength={1024} autoComplete="new-password"/></label>)}<fieldset><legend>{t('Hlutverk','Role')}</legend>{roles.map(role=><label className={styles.role} key={role}><input type="radio" name="role" value={role} defaultChecked={role==='ADMIN'}/>{role==='ADMIN'?t('Admin · stjórnandi','Admin · administrator'):t('Starfsmaður','Operator')}</label>)}<small>{t('Nýir notendur mega ekki stofna aðra notendur.','New users cannot create other users.')}</small></fieldset>{error&&<p role="alert">{error}</p>}{success&&<p role="status">{success}</p>}<footer><button type="button" disabled={busy} onClick={()=>dialog.current.close()}>{t('Loka','Close')}</button><button disabled={busy} type="submit">{busy?'…':t('Búa til notanda','Create user')}</button></footer></form></dialog></>;
}
