"use client";

/*
 * ═══════════════════════════════════════════════════════════════
 * Language Provider
 * ═══════════════════════════════════════════════════════════════
 * Path: src/components/LanguageProvider.jsx
 * Purpose: Provide persistent Icelandic/English UI language selection and
 *          one shared translation catalogue for every pipeline.
 */

import { createContext, useContext, useEffect, useState } from "react";

export const LANGUAGE_STORAGE_KEY = "acm-pipeline-language";

const IS = {
  'Order-linked production files': 'Framleiðsluskrár tengdar pöntun',
  'Save reviewed DXF versions and download them on the machine computer.': 'Vista yfirfarnar DXF-útgáfur og sækja þær á tölvunni við vélina.',
  "Synchronizing with R2…": "Samstilli við R2…",
  "Synchronize this collection with R2": "Samstilla þetta safn við R2",
  "conflicts — both copies preserved; check the sync log": "árekstrar — bæði eintök varðveitt; skoðaðu samstillingarskrána",
  "Create a new collection…": "Búa til nýtt safn…",
  "New collection name": "Heiti nýs safns",
  "Create collection": "Búa til safn",
  "Collection created.": "Safn búið til.",
  "Keep the original design dimensions, or choose one fixed size for all selected designs.": "Halda upprunalegum málum hönnunarinnar eða velja eina fasta stærð fyrir allar valdar hannanir.",
  "Width compared with height: 16:9 is landscape, 9:16 is portrait, 1:1 is square and 4:5 is a portrait feed post.": "Breidd miðað við hæð: 16:9 er lárétt, 9:16 er lóðrétt, 1:1 er ferningur og 4:5 er lóðrétt færsla.",
  "The number of pixels in the video. More pixels preserve more detail but take longer to render. Upscaling does not create missing detail.": "Fjöldi punkta í myndbandinu. Fleiri punktar varðveita meiri smáatriði en taka lengri tíma í vinnslu. Stækkun býr ekki til smáatriði sem vantar í frumgerðina.",
  "Frames per second. 60 fps gives smoother motion; 30 fps renders fewer frames; 24 fps has a film-like cadence. Rendering time is not guaranteed to halve.": "Rammar á sekúndu. 60 fps gefur mýkri hreyfingu; 30 fps vinnur færri ramma; 24 fps gefur kvikmyndatakt. Vinnslutíminn helmingast ekki endilega.",
  "CRF controls compression, not resolution. Workshop defaults to 18; x264 defaults to 23. Lower values retain more detail and make larger files. 18: high quality, a useful starting point. 10: very little compression, much larger files. 5: even less compression, often little visible improvement over 10. 25: smaller files, with more risk of visible artefacts around text and motion. 0 is lossless; 51 is the lowest quality. There is no single best value or fixed file size: compare a short render at the intended viewing size.": "CRF stjórnar þjöppun, ekki upplausn. Sjálfgefið í Workshop er 18; sjálfgefið í x264 er 23. Lægri tala varðveitir meiri smáatriði og gefur stærri skrár. 18: mikil gæði, gott upphafsgildi. 10: mjög lítil þjöppun og mun stærri skrár. 5: enn minni þjöppun, oft lítill sýnilegur munur frá 10. 25: minni skrár en meiri hætta á sýnilegri bjögun við texta og hreyfingu. 0 er taplaust; 51 eru minnstu gæðin. Ekkert eitt gildi er algilt og skráarstærðin er ekki föst: berðu saman stutta prufu í þeirri stærð sem á að horfa á myndbandið.",
  "Render only this many seconds from the start. Leave blank for the whole animation. Use a short test to compare quality and framing.": "Vinna aðeins þennan fjölda sekúndna frá upphafi. Auður reitur merkir alla hreyfimyndina. Notaðu stutta prufu til að bera saman gæði og rammaskurð.",
  "Scale the website address in the final scene. 1 means its original size; 1.6 means 160%. This does not enlarge the whole video.": "Stækka veffangið í lokasenunni. 1 er upprunaleg stærð; 1,6 er 160%. Þetta stækkar ekki allt myndbandið.",
  "Choose a collection for the finished video, or create a new one. Design sources stay in their original collection.": "Veldu safn fyrir tilbúna myndbandið eða búðu til nýtt. Frumskrár hönnunarinnar haldast í sínu upprunalega safni.",
  "Cockpit Reconstruct": "Cockpit Endurbygging",
  "Saved scenes · every point · textured GLB": "Vistaðar Senur, hver punktur, Textúrað GLB",
  "Workshop home": "Forsíða Workshop",
  "Choose a workspace to begin.": "Veldu hluta til að byrja.",
  "Choose a tool in this workspace.": "Veldu verkfæri í þessum hluta.",
  "Open workspace": "Opna hluta",
  "Part": "Partur",

  // Claude Design - animations workspace and the zip shelf.
  "Fetch this collection from R2 to check its dependencies.": "Sæktu þetta safn af R2 til að athuga tengdar skrár.",
  "Missing or unsupported dependencies:": "Tengdar skrár vantar eða eru óstuddar:",
  "External or dynamic dependencies: verify a short render first.": "Ytri eða kvikar tengingar: yfirfarðu stutta myndbandsprufu fyrst.",
  "Supporting files and archives": "Stoðskrár og safnskrár",
  "Extract the archive before rendering.": "Afþjappaðu safnskránni áður en myndband er unnið.",
  "Component source requires an HTML entry point.": "Frumkóði íhlutar þarf HTML-inngang.",
  "Transfer to shared": "Færa yfir í shared",
  "Shared package language and device": "Tungumál og tæki fyrir shared-pakka",
  "Copying and verifying the shared package…": "Afrita og sannprófa shared-pakkann…",
  "Shared transfer failed.": "Afhending í shared mistókst.",
  "Shared package verified. Main publication is a separate step.": "Shared-pakki staðfestur. Birting á Main er sérstakt skref.",
  "Copies the selected package; originals stay in Workshop. This does not publish to Main.": "Afritar valinn pakka; frumgögn haldast í Workshop. Þetta birtir ekki efnið á Main.",
  "Claude Design": "Claude Design",
  "Design Animations": "Hreyfi Hannanir",
  "Design Archives": "Hönnunar Geymsla",
  "In ccm-workshop": "Í ccm-workshop",
  "Fetch": "Sækja niður",
  "Fetch this collection onto this machine": "Sækja þetta safn á þessa vél",
  "files": "skrár",
  "Designs in · finished video out": "Hannanir inn · tilbúið myndband út",
  "Preview a Claude Design animation, choose the frame and quality, and render it to video.": "Forskoðaðu hreyfimynd úr Claude Design, veldu ramma og gæði og búðu til myndband.",
  "The exported zip files, and which of them have not been unpacked into a folder yet.": "Exportuðu zip-skrárnar og hverjar þeirra eiga enga möppu enn.",
  "Claude Design animations": "Claude Design hreyfimyndir",
  "Collections": "Söfn",
  "Preview": "Forskoðun",
  "Refresh": "Endurnýja",
  "Reading the design library…": "Les hönnunarsafnið…",
  "Sign in again to read the design library.": "Skráðu þig inn aftur til að lesa hönnunarsafnið.",
  "No designs found in this folder.": "Engar hannanir fundust í þessari möppu.",
  "Choose a design to look at it before rendering.": "Veldu hönnun til að skoða hana áður en renderað er.",
  "Select": "Velja",
  "Select every design in this collection": "Velja allar hannanir í þessu safni",
  "Upload this collection to ccm-workshop": "Hlaða þessu safni upp í ccm-workshop",
  "This machine can render": "Þessi vél getur renderað",
  "Chromium is missing - rendering is unavailable": "Chromium vantar — ekki hægt að rendera",
  "ffmpeg is missing - rendering is unavailable": "ffmpeg vantar — ekki hægt að rendera",
  "ccm-workshop is not configured": "ccm-workshop er ekki uppsett",
  "Nothing local yet - fetch a collection from R2 first": "Ekkert staðbundið enn — sæktu safn úr R2 fyrst",
  "Video settings": "Myndbandsstillingar",
  "Frame size": "Rammastærð",
  "As each design specifies": "Eins og hönnunin segir til um",
  "One size for all of them": "Ein stærð fyrir allar",
  "Resolution": "Upplausn",
  "Frame rate": "Rammatíðni",
  "half the time": "helmingi fljótara",
  "film": "kvikmynd",
  "Quality (CRF)": "Gæði (CRF)",
  "Lower is better and larger.": "Lægra gildi = betri gæði og stærri skrá.",
  "Test length": "Prufulengd",
  "whole animation": "öll hreyfimyndin",
  "Seconds. Check the look before committing an hour.": "Sekúndur. Prófaðu útlitið áður en þú leggur klukkutíma í keyrsluna.",
  "Closing www.ccm.is": "Lokasenan — www.ccm.is",
  "Size multiplier in the last scene.": "Stækkunarstuðull í lokasenunni.",
  "Save into collection": "Vista í safn",
  "same as the design's": "sama og hönnunin",
  "Keep the player bar at the bottom of the video": "Hafa spilarastikuna sýnilega neðst í myndbandinu",
  "Off by default. It belongs to the design's own preview, not to a finished video.": "Sjálfgefið slökkt. Stikan tilheyrir forskoðun hönnunarinnar, ekki tilbúnu myndbandi.",
  "Render video": "Búa til myndband",
  "Render": "Rendera",
  "videos": "myndbönd",
  "selected": "valdar",
  "Rendering needs ffmpeg and Chromium on this machine.": "Render þarf ffmpeg og Chromium á þessari vél.",
  "Could not start the render.": "Tókst ekki að hefja render.",
  "could not be queued": "komust ekki í röð",
  "Render queue": "Render-röð",
  "waiting": "bíða",
  "Clear finished": "Hreinsa kláruð",
  "Nothing has been rendered in this session.": "Ekkert hefur verið renderað í þessari lotu.",
  "min left": "mín eftir",
  "queued": "í röð",
  "uploading": "hleð upp",
  "done": "lokið",
  "error": "villa",
  "cancelled": "hætt við",
  "Rendered videos": "Tilbúin myndbönd",
  "Nothing stored in ccm-workshop yet.": "Ekkert vistað í ccm-workshop enn.",
  "Download": "Sækja",
  "Delete": "Eyða",
  "Delete from R2": "Eyða úr R2",
  "Deleted from R2.": "Eytt úr R2.",
  "Could not delete it.": "Tókst ekki að eyða.",
  "source": "frumskrá",
  "standalone": "sjálfstæð",
  "Fetching from R2…": "Sæki úr R2…",
  "Uploading to R2…": "Hleð upp í R2…",
  "The sync failed.": "Samstillingin mistókst.",
  "fetched": "sótt",
  "uploaded": "hlaðið upp",
  "unchanged": "óbreytt",
  "Reading the archive folder…": "Les zip-möppuna…",
  "Could not read the archive folder.": "Náði ekki að lesa zip-möppuna.",
  "No zip files in this folder.": "Engar zip-skrár í þessari möppu.",
  "Every archive here has already been unpacked.": "Öll zip-skjöl hér hafa þegar verið tekin upp.",
  "archives have no folder behind them yet.": "zip-skjölum fylgir engin mappa enn.",
  "of": "af",
  "unpacked": "tekið upp",
  "not unpacked": "ekki tekið upp",
  "Unpack": "Pakka upp",
  "Unpacking…": "Pakka upp…",
  "Unpacked into": "Tekið upp í",
  "Unpacking failed.": "Upptaka mistókst.",
  "Unpacking creates a folder named after the archive. An existing folder is never overwritten.": "Upptaka býr til möppu með sama nafni og zip-skráin. Mappa sem þegar er til er aldrei yfirskrifuð.",
  "Operator workspace": "Vinnusvæði stjórnanda",
  "Pipeline navigation": "Valmynd vinnslulína",
  "Close pipeline navigation": "Loka valmynd vinnslulína",
  "Open pipeline navigation": "Opna valmynd vinnslulína",
  "Image pipeline": "Myndvinnsla",
  "Photograph in · prepared PNG out": "Ljósmynd inn · tilbúin PNG út",
  "Inputs and library": "Inntök og myndasafn",
  "Prepare images": "Undirbúa myndir",
  "Meshy pipeline": "Meshy vinnsla",
  "Images or text in · 2D/3D assets out": "Myndir eða texti inn · 2D/3D gögn út",
  "Image to 3D": "Mynd í þrívídd",
  "Multi-Image to 3D": "Margar myndir í þrívídd",
  "Text to 3D": "Texti í þrívídd",
  "Text to Image": "Texti í mynd",
  "Image to Image": "Mynd í mynd",
  "Jobs and review": "Verk og yfirferð",
  "Pipeline converter": "Skráabreytir",
  "3D/CAD in · DXF, OBJ and point clouds out": "3D/CAD inn · DXF, OBJ og punktaský út",
  "Convert and export": "Umbreyta og flytja út",
  System: "Kerfi",
  "What this machine can actually do": "Raunveruleg geta vélarinnar",
  "Python environments": "Python-umhverfi",
  "Upload source photographs and see the files available to the image and Meshy pipelines.":
    "Hladdu upp frummyndum og skoðaðu skrár sem myndavinnslan og Meshy geta notað.",
  "Restore, upscale and remove the background, then send the chosen result directly to Meshy.":
    "Endurbættu, stækkaðu og fjarlægðu bakgrunn; sendu síðan valda niðurstöðu beint í Meshy.",
  "Upload a separate Meshy image or use an image-pipeline result to generate a 3D mesh.":
    "Hladdu upp sérstakri Meshy-mynd eða notaðu niðurstöðu myndavinnslunnar til að búa til þrívítt mesh.",
  "Use several angles of the same subject to generate one more complete mesh.":
    "Notaðu nokkur sjónarhorn af sama myndefni til að búa til fullkomnara mesh.",
  "Generate a mesh directly from a written description.":
    "Búðu til mesh beint úr skriflegri lýsingu.",
  "No usable photograph? Have Meshy draw the reference instead.":
    "Engin nothæf ljósmynd? Láttu Meshy teikna viðmiðsmynd.",
  "Reference photos plus a prompt — re-light, re-frame, or clean up.":
    "Viðmiðsmyndir og fyrirmæli — breyttu lýsingu, ramma eða hreinsaðu myndina.",
  "Review every Meshy result, download its files, or hand an OBJ directly to the converter.":
    "Farðu yfir allar Meshy-niðurstöður, sæktu skrár eða sendu OBJ beint í skráabreytinn.",
  "Create printer DXF from Meshy OBJ, convert CAD/DXF to OBJ, or inspect and repair point clouds.":
    "Búðu til prent-DXF úr Meshy OBJ, breyttu CAD/DXF í OBJ eða skoðaðu og lagfærðu punktaský.",
  "Which engines are installed, and what 'auto' resolves to here.":
    "Hvaða vinnsluvélar eru uppsettar og hvað „auto“ velur á þessari vél.",
  "Not included in the current Meshy subscription.": "Ekki innifalið í núverandi Meshy-áskrift.",
  locked: "læst",

  Auto: "Sjálfvirkt",
  Light: "Ljóst",
  Dark: "Dökkt",
  "Colour theme": "Litastilling",
  Language: "Tungumál",
  Icelandic: "Íslenska",
  English: "Enska",

  Review: "Yfirferð",
  "Drag to orbit, scroll to zoom. Check the back of the head and the sides before sending anything to the converter — one view of a photograph is all Meshy had to work from.":
    "Dragðu til að snúa og skrunaðu til að þysja. Skoðaðu bakhlið höfuðs og hliðar áður en nokkuð fer í skráabreytinn — Meshy hafði aðeins eitt sjónarhorn ljósmyndarinnar.",
  All: "Öll",
  Finished: "Lokið",
  Failed: "Mistókst",
  refresh: "endurnýja",
  succeeded: "tókst",
  failed: "mistókst",
  "Nothing generated yet.": "Ekkert hefur verið búið til enn.",
  "Send to converter →": "Senda í skráabreyti →",
  download: "sækja",
  "Use for 3D →": "Nota í þrívídd →",
  "Review the local GLB, then keep or discard this complete project.":
    "Skoðaðu local GLB-skrána og veldu síðan að geyma eða henda öllu projectinu.",
  "This project failed. Discard its local files before starting another 3D job.":
    "Projectið mistókst. Hentu local skránum áður en ný þrívíddarkeyrsla hefst.",
  "Keep in R2 and clear VPS": "Geyma í R2 og hreinsa VPS",
  "Discard this project": "Henda þessu projecti",
  "Archiving and verifying…": "Vista og sannreyna…",
  "Discarding…": "Eyði…",
  "R2 archive": "R2-geymsla",
  "awaiting review decision": "bíður ákvörðunar eftir yfirferð",
  "No GLB in this job, so there is nothing to turn. Add glb to the download formats to get one.":
    "Engin GLB-skrá fylgir þessu verki og því er ekkert snúanlegt preview. GLB er skylduskrá í nýja ferlinu.",
  "No OBJ in this job. The converter reads OBJ and mesh DXF only.":
    "Engin OBJ-skrá fylgir verkinu. Skráabreytirinn les aðeins OBJ og mesh-DXF.",

  "Crystal Workshop": "Crystal Workshop",
  "Upload a model, choose what happens to it, download something the SSLE engraver reads.":
    "Veldu 3D-skrá, stilltu vinnsluna og búðu til skrá sem SSLE-grafarinn les.",
  "Meshy projects · R2 source library": "Meshy-project · R2 frumgagnasafn",
  "Finished Meshy models live in private R2 storage; choosing one copies a working file into the converter.":
    "Geymd Meshy-model eru í private R2; valin skrá er afrituð tímabundið inn í skráabreytinn.",
  "refresh library": "endurnýja safn",
  "refreshing…": "endurnýja…",
  "Reading the Meshy archive…": "Les Meshy-safnið…",
  "R2 is not available on this server.": "R2 er ekki tiltækt á þessum þjóni.",
  "No OBJ or DXF models are archived yet.": "Engin OBJ- eða DXF-model hafa verið vistuð enn.",
  "Durable R2 converter outputs": "Varanleg converter-úttök í R2",
  "No converter results are archived yet.": "Engar converter-niðurstöður hafa verið vistaðar enn.",
  "Source file": "Frumskrá",
  "Click to choose a file": "Smelltu til að velja skrá",
  "Stored in private R2 first, then streamed into the converter; large OBJ files bypass the website proxy limit":
    "Vistað fyrst í private R2 og síðan streymt í skráabreytinn; stórar OBJ-skrár fara fram hjá stærðarmörkum vefþjónsins",
  Operation: "Aðgerð",
  Options: "Stillingar",
  Results: "Niðurstöður",
  "Run conversion": "Keyra umbreytingu",
  "Converting…": "Umbreyti…",
  Stop: "Stöðva",
  "Nothing in output/ yet.": "Ekkert er komið í output/ enn.",
  "Physical blank": "Stærð kristals",
  "Effective margin": "Virk spássía",
  "Usable volume": "Nýtanlegt rúmmál",
  "Depth reference": "Dýptarviðmið",
  "on every side": "á öllum hliðum",
  "continuous depth (no layer spacing)": "samfelld dýpt (ekkert layer spacing)",
  "up to about": "allt að um",
  "planes across usable depth": "plön yfir nýtanlega dýpt",
  "or pick one of": "eða veldu eina af",
  "files already in input/": "skrám sem eru þegar í input/",
  "wrong type for this operation": "rangt skráarsnið fyrir þessa aðgerð",
  "Large meshes take a few minutes; progress appears below as it happens.":
    "Stór mesh geta tekið nokkrar mínútur; framvindan birtist hér fyrir neðan.",
  "Output appears here once a conversion starts.":
    "Úttak birtist hér þegar umbreyting hefst.",
  running: "í vinnslu",
  idle: "bíður",
  lines: "línur",
  "Point spacing controls XY density. Depth-dot spacing thins Z before layering; 0 reuses XY. Layer spacing then defines the final focus planes. “UV” below means mesh texture coordinates—not laser wavelength—so DXF output is equally suitable for a green-beam engraver.":
    "Point spacing stjórnar XY-þéttleika. Depth dot spacing grisjar Z fyrir lagskiptingu; 0 endurnotar XY. Layer spacing skilgreinir síðan fókusplönin. „UV“ merkir texture coordinates í meshinu, ekki bylgjulengd lasers; DXF hentar því jafnt fyrir green-beam grafara.",

  "Convert, resize, and slice a 3D model": "Umbreyta, stærðarsetja og sneiða 3D-model",
  "Reads common Blender-compatible 3D files, reports their geometry, sizes them in millimetres, optionally slices them, and writes every selected format. Multiple formats are also packaged as ZIP.":
    "Les algeng 3D-snið sem Blender styður, greinir formið, stærðarsetur í millimetrum, sneiðir valfrjálst og skrifar öll valin snið. Mörg snið fara einnig saman í ZIP.",
  "Model dimensions": "Mál models",
  "Declare source units and size the result in millimetres.": "Veldu einingu frumskrár og stærðarsettu niðurstöðuna í millimetrum.",
  "Source coordinate unit": "Hnitaeining frumskrár",
  "Coordinates are converted to millimetres before sizing or slicing.": "Hnitum er breytt í millimetra áður en modelið er stærðarsett eða sneitt.",
  "Millimetres (mm)": "Millimetrar (mm)",
  "Centimetres (cm)": "Sentimetrar (cm)",
  "Metres (m)": "Metrar (m)",
  "Inches (in)": "Tommur (in)",
  "Maximum model width (mm)": "Hámarksbreidd models (mm)",
  "Maximum model height (mm)": "Hámarkshæð models (mm)",
  "Maximum model depth (mm)": "Hámarksdýpt models (mm)",
  "0 keeps the converted source width. Multiple limits preserve aspect ratio and use the tightest fit.":
    "0 heldur umbreyttri frumbreidd. Mörg mörk varðveita hlutföll og þrengsta markið ræður.",
  "Placement before slicing": "Staðsetning fyrir sneiðingu",
  "Center at origin": "Miðja við núllpunkt",
  "Center X/Y and place bottom at Z=0": "Miðja X/Y og setja botn við Z=0",
  "Keep imported coordinates": "Halda innfluttum hnitum",
  "Slice model": "Sneiða model",
  "Keep geometry between optional millimetre boundaries on one axis.": "Halda formi milli valfrjálsra millimetramarka á einum ás.",
  "Slice axis": "Sneiðingarás",
  "Do not slice": "Ekki sneiða",
  "X · width": "X · breidd",
  "Y · height": "Y · hæð",
  "Z · depth": "Z · dýpt",
  "Keep from coordinate (mm)": "Halda frá hniti (mm)",
  "Keep through coordinate (mm)": "Halda að hniti (mm)",
  "Blank leaves this side open. Coordinates are measured after unit conversion, fitting, and placement.":
    "Tómt gildi skilur þessa hlið opna. Hnit eru mæld eftir einingabreytingu, stærðarsetningu og staðsetningu.",
  "Cap cut surfaces": "Loka skurðflötum",
  "Fills closed cut loops when the source topology allows it.": "Fyllir lokaðar skurðlykkjur þegar topology frumskrár leyfir.",
  "Output formats": "Úttakssnið",
  "DXF uses ACM's SSLE POINT-cloud writer. Two or more selections also produce one ZIP.":
    "DXF notar SSLE POINT-punktaskýsskrifara ACM. Tvö eða fleiri val búa einnig til eina ZIP-skrá.",
  "DXF sampling target (0 = spacing)": "DXF sampling-markmið (0 = spacing)",
  "Only used when DXF is selected.": "Aðeins notað þegar DXF er valið.",
  "DXF point spacing (mm)": "DXF punktabil (mm)",
  "DXF minimum dot distance (mm)": "DXF lágmarks punktabil (mm)",
  "DXF depth-dot spacing (mm)": "DXF dýptarpunktabil (mm)",
  "DXF final point cap": "DXF hámarksfjöldi lokapunkta",
  "DXF sampling seed": "DXF sampling-seed",

  "Crystal size": "Kristalstærð",
  "Aspect ratio is always preserved.": "Hlutföll modelsins haldast alltaf óbreytt.",
  "Crystal blank": "Kristall",
  "Width x height x depth in mm.": "Breidd × hæð × dýpt í millimetrum.",
  "Custom width (mm)": "Sérsniðin breidd (mm)",
  "Custom height (mm)": "Sérsniðin hæð (mm)",
  "Custom depth (mm)": "Sérsniðin dýpt (mm)",
  "Custom border (mm)": "Sérsniðin spássía (mm)",
  "Crystal margin (mm)": "Bil frá kristalbrún (mm)",
  "0 keeps the blank above.": "0 notar valda kristalstærð.",
  "Usually the limit for a full 3D subject. Raise it to get the model bigger.":
    "Dýptin takmarkar venjulega fullt 3D-myndefni. Hækkaðu gildið til að stækka modelið.",
  "Unengraved margin on every side. 0 keeps the blank preset; 0.1 mm is allowed for a precisely calibrated laser.":
    "Ógrafið bil á öllum hliðum. 0 notar sjálfgefna spássíu kristalsins; 0,1 mm er leyft fyrir nákvæmlega kvarðaðan laser.",
  "Unengraved margin on every side. The standard is 1 mm; enter any value down to 0.1 mm.":
    "Ógrafið bil frá hverri kristalbrún. Staðalgildið er 1 mm; hægt er að skrifa inn hvaða gildi sem er niður í 0,1 mm.",
  "Dot density": "Punktaþéttleiki",
  "How many laser dots, and how close together.": "Fjöldi laserpunkta og bil þeirra á milli.",
  "Sampling target (0 = spacing)": "Sampling-markmið (0 = spacing)",
  "Point spacing (XY, mm)": "Point spacing (XY, mm)",
  "Minimum dot distance (mm)": "Lágmarks punktabil (mm)",
  "Depth dot spacing before layers (mm)": "Dýptarpunktabil fyrir lög (mm)",
  "Final point cap": "Hámarksfjöldi lokapunkta",
  "Depth layers": "Dýptarlög",
  "Snap depth onto planes the laser focuses on.": "Festa dýptarpunkta á fókusplön lasersins.",
  "Fixed plane count (alternative)": "Fastur fjöldi plana (valkostur)",
  "Layer spacing (mm)": "Layer spacing (mm)",
  Stagger: "Hliðrun laga",
  "Offsets alternate layers so dots do not stack into visible columns.":
    "Hliðrar lögum til skiptis svo punktar staflist ekki í sýnilegar súlur.",
  "Texture toning": "Texture-tónun",
  "Drive dot density from image brightness.": "Láta birtu myndar stjórna punktaþéttleika.",
  "Texture image": "Texture-mynd",
  "Lookup mode": "Texture-vörpun",
  "Mesh UV coordinates": "UV-hnit meshsins",
  "Front projection": "Vörpun að framan",
  Toning: "Tónun",
  "Density floor": "Lágmarksþéttleiki",
  "Invert brightness": "Snúa við birtu",
  Orientation: "Snúningur og stefna",
  "Which way the subject sits in the glass.": "Hvernig myndefnið snýr inni í kristalnum.",
  "Keep upright": "Halda uppréttu",
  "Axis facing the viewer": "Ás sem snýr að áhorfanda",
  "Auto-orient for biggest fit": "Sjálfvirk stefna fyrir stærstu fyllingu",
  "Swap Y and Z": "Víxla Y og Z",
  "Mirror axes": "Spegla ása",
  Output: "Úttak",
  Seed: "Seed",
  "Also write XYZ preview": "Skrifa einnig XYZ-preview",
  "The seed fixes pseudo-random surface sampling. The same input, settings and seed reproduce the same cloud; changing any of them can change the dots.":
    "Seed festir slembiúrtak yfirborðsins. Sama inntak, sömu stillingar og sama seed endurskapa sama punktaský; breyting á einhverju þeirra getur breytt punktunum.",
  "UV means the mesh's 2D texture coordinates, not an ultraviolet laser. It is unrelated to UV versus green-beam engraving.":
    "UV merkir tvívíð texture-hnit meshsins, ekki ultraviolet laser. Þetta tengist ekki UV- eða green-beam gröfun.",

  Photo: "Ljósmynd",
  "Reference images": "Viðmiðsmyndir",
  "Click to add images": "Smelltu til að bæta við myndum",
  "Or run the image pipeline first and send the result here":
    "Eða keyrðu myndavinnsluna fyrst og sendu niðurstöðuna hingað",
  remove: "fjarlægja",
  "Generate 3D": "Búa til þrívídd",
  "Generating…": "Bý til…",
  "This run": "Þessi keyrsla",
  "open jobs and review →": "opna verk og yfirferð →",
  "Download formats": "Niðurhalssnið",
  "Chooses which files Meshy generates and this server downloads. GLB is mandatory for the local review gate; OBJ enables direct converter handoff.":
    "Velur skrárnar sem Meshy býr til. GLB er skylduskrá fyrir local yfirferð; OBJ gerir beina sendingu í skráabreytinn mögulega.",
  "Generate texture": "Búa til texture",
  "Texture resolution": "Texture-upplausn",
  "Texture prompt": "Texture-fyrirmæli",
  "PBR maps": "PBR-kort",
  "Transparent thumbnail": "Gegnsæ thumbnail-mynd",
  "Four-view thumbnails": "Thumbnail-myndir frá fjórum hliðum",
  Origin: "Uppruni",
  "Scale the model to that size": "Skala modelið í þessa stærð",
  "Generation model": "Meshy-model",
  "Which Meshy engine builds the geometry.": "Hvaða Meshy-vél býr til formið.",
  "Mesh and topology": "Mesh og topology",
  "What the surface is made of.": "Hvernig yfirborðið er byggt upp.",
  Texture: "Texture",
  "Leave off for engraving - the glass has no colour.": "Hafðu slökkt fyrir gröfun — kristallinn notar ekki liti.",
  "Crystal fit": "Aðlögun að kristal",
  "Which blank this model is destined for.": "Fyrir hvaða kristal modelið er ætlað.",
  "AI model": "AI-model",
  "Model type": "Gerð models",
  "Smart Topology face count": "Fjöldi flata í Smart Topology",
  "Ultra mode": "Ultra-hamur",
  "Meshy image enhancement": "Myndabæting Meshy",
  "Remove baked lighting": "Fjarlægja fasta lýsingu",
  "Force pose": "Þvinga líkamsstöðu",
  "Content moderation": "Efnisöryggisskoðun",
  Remesh: "Endurbyggja mesh",
  Topology: "Topology",
  "Target polycount": "Markfjöldi flata",
  "Adaptive decimation": "Aðlagandi fækkun flata",
  "Keep the pre-remesh model too": "Geyma einnig modelið fyrir remesh",
  "Image model": "Myndamodel",
  "Aspect ratio": "Myndhlutföll",
  "Generate multiple views": "Búa til mörg sjónarhorn",
  "Transparent background": "Gegnsær bakgrunnur",
  Prompt: "Fyrirmæli",
  "Chooses the standard geometry engine. Latest currently resolves to Meshy 7; Smart Topology selects Meshy T2 automatically instead.":
    "Velur hefðbundna form-vél. Latest notar nú Meshy 7; Smart Topology velur Meshy T2 sjálfvirkt.",
  "Standard preserves maximum surface detail. Smart Topology automatically uses Meshy T2, costs 5 credits, and caps the directly generated mesh at 15,000 faces.":
    "Standard varðveitir mest yfirborðssmáatriði. Smart Topology notar Meshy T2, kostar 5 credits og takmarkar mesh við 15.000 fleti.",
  "Meshy T2 generates directly at this approximate face count. Higher preserves more form; 15,000 is the API maximum.":
    "Meshy T2 býr modelið til með um það bil þessum fjölda flata. Hærra gildi varðveitir meira form; 15.000 er hámark API.",
  "Meshy 7 only. Adds 5 credits and generates finer geometry natively; it improves surfaces, not texture resolution.":
    "Aðeins Meshy 7. Bætir við 5 credits og býr til nákvæmara form; þetta bætir yfirborð en ekki texture-upplausn.",
  "Lets Meshy optimize the reference before reconstruction. It is independent of the local image pipeline; turn it off only when exact source appearance matters.":
    "Leyfir Meshy að bæta viðmiðsmyndina fyrir þrívíddarvinnslu. Þetta er óháð local myndavinnslunni; slökktu aðeins þegar nákvæmt útlit frummyndar skiptir máli.",
  "Meshy 6 texture option that removes highlights and shadows from base colour. It does not repair geometry and is omitted for other models.":
    "Meshy 6 texture-stilling sem fjarlægir glampa og skugga úr grunnlit. Hún lagar ekki form og er ekki notuð með öðrum modelum.",
  "Constrains a full-body character to an A- or T-pose. Leave off for portraits, busts, pets, objects and buildings.":
    "Setur heila manneskju í A- eða T-stöðu. Hafðu slökkt fyrir portrett, brjóstmyndir, dýr, hluti og byggingar.",
  "Screens image and prompt content before generation. Keep it on for customer material; a rejected task does not proceed.":
    "Öryggisskoðar mynd og fyrirmæli fyrir vinnslu. Hafðu kveikt fyrir efni viðskiptavina; hafnað verk er ekki keyrt.",
  "Rebuilds and decimates the surface. Leave it off for crystal engraving so the converter receives Meshy's raw high-density geometry.":
    "Endurbyggir og fækkar flötum. Hafðu slökkt fyrir kristalgröfun svo skráabreytirinn fái óskert háþéttniform Meshy.",
  "Triangle creates a decimated triangle mesh; quad creates a quad-dominant mesh. This applies only when Remesh is enabled.":
    "Triangle býr til fækkað þríhyrningsmesh; quad býr til að mestu fjórhyrningsmesh. Gildir aðeins þegar Remesh er virkt.",
  "Approximate face count after remeshing, from 100 to 300,000. Higher preserves more detail but creates larger files and slower conversion.":
    "Áætlaður fjöldi flata eftir remesh, 100–300.000. Hærra gildi varðveitir meiri smáatriði en býr til stærri skrár og hægari umbreytingu.",
  "Adaptive decimation overrides Target polycount: 1 is ultra, 2 high, 3 medium and 4 low. Leave off to use an exact target.":
    "Adaptive decimation tekur yfir Target polycount: 1 er ultra, 2 hátt, 3 miðlungs og 4 lágt. Hafðu slökkt til að nota nákvæmt markgildi.",
  "Also returns the dense GLB from before remeshing, so the reduced result can be compared or bypassed. Applies only when Remesh is on.":
    "Skilar einnig þéttu GLB fyrir remesh svo hægt sé að bera saman eða sleppa fækkuðu útgáfunni. Gildir aðeins þegar Remesh er virkt.",
  "Adds a colour-texture pass (normally 10 credits). Crystal engraving reads geometry only, so leave this off unless you also need a rendered model.":
    "Bætir við litatexture-vinnslu (venjulega 10 credits). Kristalgröfun les aðeins form, svo hafðu slökkt nema einnig þurfi litað render.",
  "Controls base-colour texture size. 2K and 4K cost the same; 8K adds 5 credits and substantially increases downloads.":
    "Stjórnar stærð grunnlita-texture. 2K og 4K kosta jafnt; 8K bætir við 5 credits og stækkar niðurhal verulega.",
  "Adds metallic, roughness and normal maps (and emission where supported). These improve rendered materials but have no effect in engraved glass.":
    "Bætir við metallic-, roughness- og normal-kortum. Þau bæta renderuð efni en hafa engin áhrif í gröfnum kristal.",
  "Up to 600 characters describing colours and materials. It guides only the texture pass and does not change the generated shape.":
    "Allt að 600 stafir um liti og efni. Þetta stýrir aðeins texture-vinnslu og breytir ekki formi modelsins.",
  "Recorded on the job and pre-selected when you hand the model to the converter.":
    "Vistað með verkinu og forvalið þegar modelið er sent í skráabreytinn.",
  "Physical crystal height. Meshy subtracts the top and bottom margin before resizing; 0 uses the selected blank.":
    "Raunhæð kristalsins. Meshy dregur margin efst og neðst frá áður en modelið er skalað; 0 notar valda kristalstærð.",
  "Physical crystal width carried into the converter. Set 0 to use the selected blank.":
    "Raunbreidd kristalsins sem flyst yfir í skráabreytinn. 0 notar valda kristalstærð.",
  "Physical crystal depth carried into the converter. Depth usually limits a full 3D subject.":
    "Raundýpt kristalsins sem flyst yfir í skráabreytinn. Dýptin takmarkar yfirleitt stærð fulls þrívídds myndefnis.",
  "Carried over to the converter. Depth is what usually limits a full 3D subject.":
    "Flyst yfir í skráabreytinn. Dýptin takmarkar yfirleitt stærð fulls þrívídds myndefnis.",
  "+5 credits for a Meshy remesh that resizes the export to real millimetres. Off is fine - the converter refits it anyway - but it makes the downloaded file measure correctly in Blender or a slicer.":
    "+5 credits fyrir Meshy-remesh sem skalar útflutning í raunmillimetra. Slökkt er í lagi því skráabreytirinn aðlagar modelið; virkt gefur rétta stærð í Blender eða slicer.",
  "+5 credits. Meshy resizes by usable height only; the converter later enforces the same margin across width, height and depth.":
    "+5 credits. Meshy skalar aðeins eftir nýtanlegri hæð; skráabreytirinn tryggir síðan sama margin á breidd, hæð og dýpt.",
  "Requests a transparent preview image when Meshy supports it. This affects only the thumbnail, never the model geometry.":
    "Biður um gegnsæja preview-mynd þegar Meshy styður það. Hefur aðeins áhrif á thumbnail, aldrei form modelsins.",
  "Requests front, right, back and left review renders. They are the quickest way to spot missing or collapsed geometry before conversion.":
    "Biður um preview að framan, hægri, aftan og vinstri. Fljótlegasta leiðin til að finna vantað eða fallið form fyrir umbreytingu.",
  "Centre is what the point-cloud sampler expects - it fits a model about its own middle.":
    "Center er það sem punktaskýsvinnslan gerir ráð fyrir; modelið er aðlagað um miðju sína.",
  "Returns three consistent angles and charges for three images. They can be reviewed individually; combining them into one mesh requires Multi-Image to 3D access.":
    "Skilar þremur samræmdum sjónarhornum og rukkar fyrir þrjár myndir. Hægt er að skoða þær hverja fyrir sig; sameining í eitt mesh krefst Multi-Image to 3D aðgangs.",
  "Returns an RGBA PNG with transparency. This is usually the cleanest direct input for Image to 3D.":
    "Skilar RGBA PNG með gegnsæi. Þetta er yfirleitt hreinasta beina inntakið fyrir Image to 3D.",
  "3D model to printable DXF": "3D-model í prentanlegt DXF",
  "Samples an OBJ or triangle-mesh DXF into the evenly spaced POINT cloud the SSLE engraver reads, fitted to a crystal blank.":
    "Umbreytir OBJ eða triangle-mesh DXF í jafndreift POINT-punktaský fyrir SSLE-grafarann og aðlagar það að völdum kristal.",
  "Repair or re-tune a point DXF": "Laga eða endurstilla punkta-DXF",
  "Re-emits an existing POINT cloud in the exact format the printer accepts. Use it when a Cockpit3D export will not load, or to change size, dot spacing and depth layers without going back to the model.":
    "Endurskrifar POINT-punktaský á nákvæmu sniði grafarans. Notað þegar Cockpit3D-skrá opnast ekki eða til að breyta stærð, punktabili og dýptarlögum án upprunalegs models.",
  "Point DXF to standards-compliant DXF": "Punkta-DXF í staðlað DXF",
  "Rebuilds a bare Cockpit3D POINT export as a full AC1015 file with tables, blocks and real handles, so any CAD tool opens it.":
    "Endurbyggir einfalt Cockpit3D POINT-úttak sem fulla AC1015-skrá með töflum, blokkum og handles svo CAD-forrit geti opnað hana.",
  "Point DXF to mesh or cloud": "Punkta-DXF í mesh eða punktaský",
  "Turns a POINT-cloud DXF back into XYZ, PLY, OBJ or STL. The reverse direction, for viewing and 3D printing.":
    "Breytir POINT-DXF aftur í XYZ, PLY, OBJ eða STL fyrir skoðun og þrívíddarprentun.",
  "Cockpit3D CAD to mesh or cloud": "Cockpit3D CAD í mesh eða punktaský",
  "Reads the proprietary CIRasterizer text format and exports XYZ, PLY, OBJ or STL.":
    "Les CIRasterizer textasnið Cockpit3D og flytur út XYZ, PLY, OBJ eða STL.",
  "Inspect a file": "Skoða skrá",
  "Reports what a file actually contains before you convert it. Changes nothing on disk.":
    "Sýnir raunverulegt innihald skráar fyrir umbreytingu án þess að breyta neinu.",
  "Optional sampling target before thinning. Keep 0 for Cockpit3D-style density controlled by point spacing.":
    "Valfrjálst sampling-markmið fyrir grisjun. Hafðu 0 fyrir Cockpit3D-líkan þéttleika sem point spacing stjórnar.",
  "Main Cockpit3D-style density control. 0.08 mm is the reference baseline; smaller values create more dots.":
    "Aðalstýring punktaþéttleika eins og í Cockpit3D. 0,08 mm er viðmið; lægra gildi býr til fleiri punkta.",
  "Safety floor between XY dots. Start at the 0.08 mm Cockpit3D reference and validate any smaller distance on the green-beam machine.":
    "Öryggislágmark milli XY-punkta. Byrjaðu á 0,08 mm Cockpit3D-viðmiði og prófaðu minna bil sérstaklega á green-beam vélinni.",
  "Grid-thinning distance along Z before points are snapped to final layers. 0 reuses XY point spacing; this is not layer spacing.":
    "Grisjunarbil eftir Z áður en punktar festast á lokaplön. 0 endurnotar XY point spacing; þetta er ekki layer spacing.",
  "Cockpit3D reference guardrail. 500,000 limits oversized clouds after spacing and layers; 0 removes the cap.":
    "Cockpit3D-öryggisviðmið. 500.000 takmarkar of stór punktaský eftir spacing og lög; 0 fjarlægir hámarkið.",
  "Alternative to layer spacing. 0 lets the millimetre spacing below decide the number of depth planes.":
    "Valkostur við layer spacing. 0 lætur millimetrabilið hér fyrir neðan ákvarða fjölda dýptarplana.",
  "auto uses GFPGAN on CUDA and Pillow on CPU. Choose GFPGAN explicitly for slower CPU AI restoration.":
    "auto notar GFPGAN með CUDA en Pillow á CPU. Veldu GFPGAN sérstaklega fyrir hægari AI-andlitsviðgerð á CPU.",
  "auto uses Real-ESRGAN on CUDA and Lanczos on CPU. Choose Real-ESRGAN explicitly for slower CPU AI upscaling.":
    "auto notar Real-ESRGAN með CUDA en Lanczos á CPU. Veldu Real-ESRGAN sérstaklega fyrir hægari AI-stækkun á CPU.",
  Uploaded: "Upphlaðið",
  "Waiting in the image pipeline's input folder.": "Bíður í input-möppu myndavinnslunnar.",
  Cleaned: "Unnið",
  "What the Image pipeline produced. Every stage is kept, so pick the one that looks right.":
    "Niðurstöður myndavinnslunnar. Öll millistig eru geymd svo hægt sé að velja bestu útgáfuna.",
  "Ready for Meshy": "Tilbúið fyrir Meshy",
  "Meshy generation screens pick from this dedicated folder.":
    "Meshy-vinnsluskjáir velja myndir úr þessari sérstöku möppu.",

  // Workshop area inside Crystal Studio: data-file help, Reconstruct, R2 browser, scenes and environments (28-09-2026).
  "Orders & DXF files": "Pantanir og DXF-skrár",
  "Rebuild exported DXF or CAD points as a colored surface and review the GLB.": "Endurbyggðu útflutta DXF- eða CAD-punkta sem litað yfirborð og yfirfarðu GLB-skrána.",
  "R2 File Browser": "R2-skráasafn",
  "Browse, download and use files from private R2 storage.": "Flettu í, sæktu og notaðu skrár úr lokaðri R2-geymslu.",
  "Restore": "Lagfæra",
  "Upscale": "Stækka",
  "Cut out": "Klippa út",
  "Repair a soft or aged photograph.": "Lagfæra óskýra eða gamla ljósmynd.",
  "More pixels for Meshy to read edges from.": "Fleiri punktar svo Meshy greini brúnir betur.",
  "Isolate the subject on transparency.": "Einangra myndefnið á gegnsæjum bakgrunni.",
  "Restore the photograph": "Lagfæra ljósmyndina",
  "Worth it on old or soft photographs. Skip it on a sharp modern one.": "Borgar sig á gömlum eða óskýrum ljósmyndum. Slepptu því á skarpri nýlegri mynd.",
  "Restore engine": "Lagfæringarvél",
  "Face fidelity": "Trúnaður við andlit",
  "GFPGAN only. 0 rebuilds aggressively, 1 stays close to the original face.": "Aðeins GFPGAN. 0 endurbyggir andlitið mikið, 1 heldur sig nálægt upprunalega andlitinu.",
  "Brightness": "Birta",
  "Contrast": "Birtuskil",
  "Contrast and sharpness are what Meshy actually reads as form.": "Birtuskil og skerpa eru það sem Meshy les í raun sem lögun.",
  "Sharpness": "Skerpa",
  "Saturation": "Litmettun",
  "Upscale the photograph": "Stækka ljósmyndina",
  "Skipped automatically when the photo already exceeds the target.": "Sleppt sjálfkrafa ef ljósmyndin er þegar stærri en markstærðin.",
  "Upscale engine": "Stækkunarvél",
  "Target long edge (px)": "Markstærð lengri hliðar (px)",
  "Remove the background": "Fjarlægja bakgrunninn",
  "The single biggest win before Meshy - it stops the sofa behind a shoulder becoming part of the bust.": "Mikilvægasta skrefið fyrir Meshy: það kemur í veg fyrir að sófinn fyrir aftan öxlina verði hluti af brjóstmyndinni.",
  "Cut-out model": "Útklippingarlíkan",
  "BiRefNet gives the cleanest edges but uses the most RAM. isnet-general-use is the balanced CPU choice; u2netp is the smallest safe fallback on a constrained VPS.": "BiRefNet gefur hreinustu brúnirnar en notar mest vinnsluminni. isnet-general-use er jafnvægisval fyrir CPU; u2netp er minnsti örugga varakosturinn á takmörkuðum VPS.",
  "Alpha matting": "Alpha-mötun",
  "Slower, but recovers fine hair against a busy background.": "Hægara, en nær fínu hári á móti flóknum bakgrunni.",
  "Override saved Cockpit pose": "Yfirskrifa vistaða Cockpit-stöðu",
  "Normally read from the paired scene. Enable only to enter the absolute rotation and position used when the DXF was exported; these replace the saved values, not add to them.": "Lesið úr paraðri senu að jafnaði. Virkjaðu aðeins til að slá inn nákvæman snúning og staðsetningu sem notuð voru þegar DXF var flutt út; gildin koma í stað vistuðu gildanna en bætast ekki við þau.",
  "Absolute Cockpit Layer Specs value for the exported model. Rotation is undone for texture projection and restored afterward. Center at origin removes the final translation; disable centering to preserve scene position.": "Nákvæmt Layer Specs-gildi úr Cockpit fyrir útflutta líkanið. Snúningur er afturkallaður fyrir áferðarvörpun og settur aftur á eftir. Miðjun í núllpunkti fjarlægir lokahliðrunina; slökktu á miðjun til að halda stöðu senunnar.",
  "Sample every Nth point": "Taka N-ta hvern punkt",
  "Keep 1 to use every source point. Showroom preparation always uses all points. The output grid separately controls surface resolution.": "Haltu 1 til að nota alla upprunapunkta. Undirbúningur fyrir sýningarsal notar alltaf alla punkta. Úttaksnetið stýrir upplausn yfirborðsins sérstaklega.",
  "Surface vertex budget": "Hámark hnútpunkta á yfirborði",
  "A hard limit before triangulation. Approved showroom budget: 500,000 surface vertices.": "Föst hámarkstala fyrir þríhyrningun. Samþykkt hámark fyrir sýningarsal: 500.000 hnútpunktar.",
  "First points only (0 = all)": "Aðeins fyrstu punktar (0 = allir)",
  "Use 5,000 for a quick diagnostic. A partial scan can crop the subject.": "Notaðu 5.000 fyrir snögga greiningu. Hlutaskönnun getur skorið af myndefninu.",
  "Surface method": "Yfirborðsaðferð",
  "Continuous relief · recommended": "Samfellt relief · ráðlagt",
  "Raw triangles · comparison": "Hráir þríhyrningar · til samanburðar",
  "Closed outer hull · Convex": "Lokaður ytri hjúpur · kúpt",
  "Continuous relief collapses laser layers and avoids triangles across empty background.": "Samfellt relief sameinar laserlög og forðast þríhyrninga yfir auðan bakgrunn.",
  "Relief resolution": "Upplausn relief",
  "Grid samples along the longer edge. 768 is the approved showroom default.": "Fjöldi netpunkta eftir lengri hliðinni. 768 er samþykkt sjálfgildi fyrir sýningarsal.",
  "Depth smoothing": "Dýptarjöfnun",
  "Removes laser-layer roughness. Higher values can soften facial detail.": "Fjarlægir hrjúfleika laserlaga. Hærri gildi geta mýkt smáatriði í andliti.",
  "Close silhouette gaps": "Loka götum í útlínum",
  "Close small contour breaks, then interpolate enclosed dark areas. 0 leaves holes.": "Lokar litlum rofum í útlínum og fyllir svo lokuð dökk svæði. 0 skilur eftir göt.",
  "Front layer percentile": "Hundraðshlutamark fremsta lags",
  "85 estimates the front surface while rejecting isolated outermost dots.": "85 áætlar fremra yfirborðið en hafnar stökum ystu punktum.",
  "Front of relief": "Framhlið relief",
  "Positive Z is toward the viewer. Try negative if the surface faces backward.": "Jákvætt Z snýr að áhorfanda. Prófaðu neikvætt ef yfirborðið snýr aftur.",
  "Repair lower-body ridges (experimental)": "Laga hryggi á neðri hluta (tilraun)",
  "Reduces narrow protrusions in the bottom 42%. Upper geometry stays unchanged.": "Minnkar mjóar útskotur í neðstu 42%. Efri hluti lögunarinnar helst óbreyttur.",
  "Lower-body repair strength": "Styrkur viðgerðar á neðri hluta",
  "Higher values pull wider ridges toward the surrounding surface; review hand detail.": "Hærri gildi draga breiðari hryggi að nærliggjandi yfirborði; yfirfarðu smáatriði í höndum.",
  "Photo detail": "Smáatriði ljósmyndar",
  "Full photo texture · recommended": "Full ljósmyndaáferð · ráðlagt",
  "Vertex colors · comparison": "Litir á hnútpunktum · til samanburðar",
  "A photo texture keeps fine details without requiring more triangles.": "Ljósmyndaáferð heldur fínum smáatriðum án þess að þurfa fleiri þríhyrninga.",
  "Paired scene or photograph": "Pöruð sena eða ljósmynd",
  "Optional. Without a photo the surface stays light grey.": "Valfrjálst. Án ljósmyndar helst yfirborðið ljósgrátt.",
  "Photo projection plane": "Vörpunarflötur ljósmyndar",
  "XY matches the original relief preset. Auto requires a recognized scene direction.": "XY samsvarar upprunalegu relief-forstillingunni. Auto krefst þekktrar stefnu senunnar.",
  "Reverse the photo left to right without changing the mesh. Normally leave off for the original Cockpit texture.": "Snúa ljósmyndinni við frá vinstri til hægri án þess að breyta netinu. Hafðu slökkt að jafnaði fyrir upprunalegu Cockpit-áferðina.",
  "Mirror photo horizontally": "Spegla ljósmynd lárétt",
  "Reverse the photo top to bottom without changing geometry. Leave off unless the source orientation requires correction.": "Snúa ljósmyndinni við ofan frá og niður án þess að breyta lögun. Hafðu slökkt nema stefna frumgagna þurfi leiðréttingu.",
  "Mirror photo vertically": "Spegla ljósmynd lóðrétt",
  "Remove identical coordinates before reconstruction. The approved preset leaves this off to preserve the original point distribution.": "Fjarlægja eins hnit fyrir endurbyggingu. Samþykkta forstillingin hefur slökkt á þessu til að halda upprunalegri dreifingu punkta.",
  "Remove duplicate points": "Fjarlægja tvítekna punkta",
  "Translate the finished surface to its bounding-box centre. Disable to preserve the original Cockpit position in millimetres.": "Færa tilbúna yfirborðið í miðju umlykjandi kassa. Slökktu til að halda upprunalegri Cockpit-staðsetningu í millimetrum.",
  "Center surface at origin": "Miðja yfirborð í núllpunkti",
  "Pins a source axis to crystal height so a tall subject is not laid on its side.": "Festir ás frumgagna við hæð kristalsins svo hátt myndefni leggist ekki á hliðina.",
  "Two mappings often tie on size but show completely different sides.": "Tvær varpanir gefa oft sömu stærð en sýna gjörólíkar hliðar.",
  "Maximises size, but may rotate the subject. Leave off when using Keep upright.": "Hámarkar stærð en getur snúið myndefninu. Hafðu slökkt þegar Keep upright er notað.",
  "For Z-up sources such as CAD exports.": "Fyrir frumgögn þar sem Z snýr upp, t.d. CAD-útflutning.",
  "Cockpit3D layer-spacing equivalent. 0.09 mm is the owner-approved layer-spacing baseline and overrides the fixed plane count.": "Samsvarar layer spacing í Cockpit3D. 0,09 mm er viðmið sem eigandi samþykkti og tekur fram yfir fastan fjölda plana.",
  "Photo brightness controls DXF points (experimental)": "Birta ljósmyndar stýrir DXF-punktum (tilraun)",
  "Experimental portrait sampling, not a validated machine preset. Use the UV photograph to place more points in bright regions and no points in black regions. Requires one image texture; bake multiple materials in Blender first.": "Tilraunasýnataka fyrir andlitsmyndir, ekki staðfest vélarforstilling. Notar UV-ljósmyndina til að setja fleiri punkta á björt svæði og enga á svört svæði. Krefst einnar myndáferðar; bakaðu mörg efni saman í Blender fyrst.",
  "Bright areas get denser dots. This is what makes glass read as a photograph.": "Björt svæði fá þéttari punkta. Það er þetta sem lætur glerið líta út eins og ljósmynd.",
  "Gamma on brightness. Cockpit3D's own default is 1.8; higher deepens shadows.": "Gamma á birtu. Sjálfgildi Cockpit3D er 1,8; hærra gildi dýpkar skugga.",
  "Keeps the darkest areas sparse rather than completely empty.": "Heldur dekkstu svæðunum gisnum frekar en alveg tómum.",
  "Treat dark as dense instead of light.": "Meðhöndla dökkt sem þétt í stað ljóss.",
  "Refit into a crystal blank": "Laga að kristalauðu",
  "Leave off for a pure format repair that moves no coordinate.": "Hafðu slökkt fyrir hreina sniðviðgerð sem færir engin hnit.",
  "Plain scale factor": "Einfaldur stærðarstuðull",
  "Multiplier about the centre, when refitting is too much.": "Margfaldari um miðjuna, þegar aðlögun er of mikil.",
  "Re-space dots (mm)": "Endurdreifa punktum (mm)",
  "0 keeps every point. Cannot add detail the source does not already have.": "0 heldur öllum punktum. Getur ekki bætt við smáatriðum sem eru ekki í frumgögnunum.",
  "Grid-thinning distance along Z before final layer snapping. 0 reuses XY spacing; it is separate from layer spacing.": "Grisjunarfjarlægð eftir Z áður en punktar eru festir við lög. 0 notar XY-bilið aftur; það er aðskilið frá bili milli laga.",
  "Point cap": "Hámark punkta",
  "500,000 is the Cockpit3D reference guardrail. Set 0 only when no cap is wanted.": "500.000 er viðmiðunarhámark Cockpit3D. Settu 0 aðeins ef ekkert hámark á að vera.",
  "Point limit": "Punktamörk",
  "0 keeps every point.": "0 heldur öllum punktum.",
  "Scale factor": "Stærðarstuðull",
  "Remove duplicates": "Fjarlægja tvítekningar",
  "Reconstruction failed.": "Endurbygging mistókst.",
  "GLB is ready in the working area. Download it, save it to R2, or send it to the converter.": "GLB-skráin er tilbúin á vinnusvæðinu. Sæktu hana, vistaðu á R2 eða sendu í skráarbreytinn.",
  "Finished.": "Lokið.",
  "Reconstruction stopped.": "Endurbygging stöðvuð.",
  "R2 publication failed.": "Vistun á R2 mistókst.",
  "Saved to R2: {key}. Choose the model in the showroom admin to publish it.": "Vistað á R2: {key}. Veldu módelið í showroom-admin til að birta það.",
  "Handoff failed.": "Afhending mistókst.",
  "Cockpit exports → surfaces": "Cockpit-útflutningur → yfirborð",
  "Choose your point export and its original Cockpit scene, then create a textured GLB.": "Veldu punktaútflutninginn og upprunalegu Cockpit-senuna hans og búðu svo til GLB með áferð.",
  "01 · Choose Cockpit scene": "01 · Veldu Cockpit-senu",
  "02 · Choose matching DXF": "02 · Veldu samsvarandi DXF",
  "03 · Create GLB": "03 · Búðu til GLB",
  "Selection changed. Load the selected scene pair before creating a GLB.": "Valið breyttist. Hladdu valda senuparinu inn áður en þú býrð til GLB.",
  "R2 scene pair loaded. Saved rotation: {rotation} degrees; position: {position} mm.": "Senupar hlaðið af R2. Vistaður snúningur: {rotation} gráður; staðsetning: {position} mm.",
  "Create GLB": "Búa til GLB",
  "Original relief settings · full photo texture · no lower-body repair": "Upprunalegar relief-stillingar · full ljósmyndaáferð · engin viðgerð á neðri hluta",
  "Advanced settings": "Ítarlegri stillingar",
  "Creating GLB…": "Bý til GLB…",
  "Download original photo": "Sækja upprunalegu ljósmyndina",
  "03 · Model preview": "03 · Forskoðun líkans",
  "Building…": "Í vinnslu…",
  "Ready to review": "Tilbúið til yfirferðar",
  "Awaiting export": "Bíður útflutnings",
  "Reconstructed Cockpit relief surface": "Endurbyggt relief-yfirborð úr Cockpit",
  "Your piece, reconstructed": "Verkið þitt, endurbyggt",
  "Choose an exported point cloud and build a surface. The rotating model will appear here.": "Veldu útflutt punktaský og byggðu yfirborð. Líkanið birtist hér og snýst.",
  "vertices": "hnútpunktar",
  "triangles": "þríhyrningar",
  "GLB size": "Stærð GLB",
  "Download GLB": "Sækja GLB",
  "Saving to R2…": "Vista á R2…",
  "Save to R2 Cloudflare": "Vista á R2 Cloudflare",
  "Send to converter": "Senda í skráarbreyti",
  "Download {kind}": "Sækja {kind}",
  "Temporary working files expire after seven days when the workspace next creates a job. Save to R2 to keep the result. Review the silhouette, depth and photo alignment. Continuous relief estimates the surface before laser sampling; it does not recover the original hidden mesh.": "Tímabundnar vinnuskrár renna út eftir sjö daga, næst þegar vinnusvæðið býr til verk. Vistaðu á R2 til að halda niðurstöðunni. Yfirfarðu útlínur, dýpt og hvernig ljósmyndin passar. Samfellt relief áætlar yfirborðið fyrir lasersýnatöku; það endurheimtir ekki upprunalega falda netið.",
  "Processing log": "Vinnsluskrá",
  "Advanced settings explained": "Ítarlegri stillingar útskýrðar",
  "Recommended:": "Ráðlagt:",
  "Use the saved scene value": "Nota vistað gildi senunnar",
  "Sign in to read R2.": "Skráðu þig inn til að lesa R2.",
  "Downloading a working copy from R2…": "Sæki vinnueintak af R2…",
  "Import failed.": "Innflutningur mistókst.",
  "Selected file is ready in the converter.": "Valda skráin er tilbúin í skráarbreytinum.",
  "Uploading the edited GLB to its scene folder…": "Hleð breyttu GLB-skránni upp í möppu senunnar…",
  "This upload supports GLB files up to 64 MB.": "Þessi upphleðsla styður GLB-skrár allt að 64 MB.",
  "Upload failed.": "Upphleðsla mistókst.",
  "Saved to R2. Choose Use in converter to create DXF.": "Vistað á R2. Veldu Nota í skráarbreyti til að búa til DXF.",
  "Storage area": "Geymslusvæði",
  "R2 folder path": "Slóð R2-möppu",
  "Upload GLB from Blender to R2": "Hlaða GLB úr Blender upp á R2",
  "Open a numbered Cockpit scene folder to upload an edited Blender GLB into that folder.": "Opnaðu númeraða Cockpit-senumöppu til að hlaða breyttri Blender-GLB upp í hana.",
  "Use in converter": "Nota í skráarbreyti",
  "R2 originals remain unchanged. Downloads are served directly from Cloudflare.": "Frumskrár á R2 haldast óbreyttar. Niðurhal kemur beint frá Cloudflare.",
  "Cockpit Reconstruct · scenes and models": "Cockpit Endurbygging · senur og módel",
  "Meshy · generated assets": "Meshy · búin til gögn",
  "Converter · exported files": "Skráarbreytir · útfluttar skrár",
  "Uploaded source files": "Upphlaðnar frumskrár",
  "Cockpit · earlier source versions": "Cockpit · eldri útgáfur frumgagna",
  "Archive": "Safn",
  "Sign in to load scenes.": "Skráðu þig inn til að sækja senur.",
  "Loading the selected pair from R2…": "Sæki valda parið af R2…",
  "Could not load scene.": "Tókst ekki að sækja senu.",
  "Scene pair ready. Every DXF point will be used with the approved defaults.": "Senuparið er tilbúið. Allir DXF-punktar verða notaðir með samþykktum sjálfgildum.",
  "Scene library": "Senusafn",
  "Refresh scene folders": "Endurhlaða senumöppum",
  "{count} files": "{count} skrár",
  "01 · Cockpit scene": "01 · Cockpit-sena",
  "Choose the saved Cockpit scene…": "Veldu vistuðu Cockpit-senuna…",
  "02 · Matching DXF / CAD": "02 · Samsvarandi DXF / CAD",
  "Choose the matching export…": "Veldu samsvarandi útflutning…",
  "Choose a Cockpit scene first": "Veldu Cockpit-senu fyrst",
  "Choose the saved scene first, then its exact export. Run the desktop R2 sync shortcut after editing files, then refresh this library.": "Veldu vistuðu senuna fyrst og svo nákvæman útflutning hennar. Keyrðu R2-samstillinguna á skjáborðinu eftir að skrám er breytt og endurhlaðaðu svo safninu.",
  "Loading…": "Hleð…",
  "Use selected scene pair": "Nota valið senupar",
  "Three Python 3.11 environments, kept separate on purpose. What is installed in each decides which engines the other steps can actually offer. An option set to auto resolves differently depending on what you see here.": "Þrjú Python 3.11-umhverfi, höfð aðskilin viljandi. Það sem er uppsett í hverju þeirra ræður hvaða vélar hin skrefin geta boðið. Valkostur stilltur á auto fer eftir því sem sést hér.",
  "checking…": "athuga…",
  "re-check": "athuga aftur",
  "ready": "tilbúið",
  "fallback": "varaleið",
  "not installed": "ekki uppsett",
  "full": "fullt",
  "degraded": "takmarkað",
  "What it can do here": "Hvað það getur gert hér",
  "Packages": "Pakkar",
  "{name} is not installed here": "{name} er ekki uppsett hér",
  "CPU-only Torch; no CUDA device": "Torch aðeins á CPU; ekkert CUDA-tæki",
  "No torch here, so the GPU engines are unavailable by design.": "Ekkert Torch hér, svo GPU-vélar eru ekki í boði, viljandi.",
  "Folders": "Möppur",
  "{count} file(s)": "{count} skrá(r)",
  "missing": "vantar",
  "Paths": "Slóðir",
  "Cached cut-out models": "Vistuð útklippingarlíkön",
  "rembg downloads these on first use, not at install time. A cold first run therefore looks like a hang, but it is a download.": "rembg sækir þau við fyrstu notkun, ekki við uppsetningu. Fyrsta keyrsla virðist því frjósa, en þetta er niðurhal.",
  "None cached yet. The first background removal will download one (birefnet-portrait is about 900 MB).": "Ekkert vistað enn. Fyrsta fjarlæging bakgrunns sækir eitt (birefnet-portrait er um 900 MB).",
  "Restores, upscales and cuts out photographs before Meshy sees them.": "Lagfærir, stækkar og klippir út ljósmyndir áður en Meshy fær þær.",
  "Background removal": "Fjarlæging bakgrunns",
  "AI upscale": "AI-stækkun",
  "Face restoration": "Andlitslagfæring",
  "Stores Meshy jobs and provides isolated diagnostics for the remote API workflow.": "Geymir Meshy-verk og veitir einangraða greiningu á fjartengda API-ferlinu.",
  "API diagnostics": "API-greining",
  "Pipeline isolation": "Einangrun vinnslu",
  "No Torch, CUDA, image models or SciPy are required in this environment.": "Þetta umhverfi þarf hvorki Torch, CUDA, myndlíkön né SciPy.",
  "Point-cloud converter": "Punktaskýjabreytir",
  "Samples a mesh into the dot cloud the SSLE engraver reads.": "Breytir neti í punktaskýið sem SSLE-lasergrafarinn les.",
  "Mesh sampling": "Sýnataka úr neti",
  "DXF reading": "Lestur DXF",
  "Expand navigation": "Opna valmynd",
  "Collapse navigation": "Loka valmynd",
  "Explain": "Útskýra",

  // Workshop area inside Crystal Studio: data-file help, Reconstruct, R2 browser, scenes and environments (28-09-2026).
  "Rotation X (degrees)": "Snúningur X (gráður)",
  "Position X (mm)": "Staðsetning X (mm)",
  "Rotation Y (degrees)": "Snúningur Y (gráður)",
  "Position Y (mm)": "Staðsetning Y (mm)",
  "Rotation Z (degrees)": "Snúningur Z (gráður)",
  "Position Z (mm)": "Staðsetning Z (mm)",
};

const LanguageContext = createContext(null);

function initialLocale() {
  if (typeof document === "undefined") return "is";
  return document.documentElement.lang === "en" ? "en" : "is";
}

// A host that knows the language on the server (Crystal Studio's language cookie) passes it
// as serverLocale, so the server render and the first client render agree.
export function LanguageProvider({ children, serverLocale }) {
  const [locale, setLocale] = useState(() => serverLocale ?? initialLocale());

  useEffect(() => {
    document.documentElement.lang = locale;
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, locale);
    } catch {
      // The language still works for this session when persistence is blocked.
    }
  }, [locale]);

  const t = (text) => (locale === "is" ? IS[text] || text : text);
  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider.");
  return value;
}
